# Pragmas.
use strict;
use warnings;

# Modules.
use ExtUtils::MakeMaker;

# Definition.
WriteMakefile(
	'AUTHOR' => 'Michal Špaček <skim@cpan.org>',
	'LICENSE' => 'bsd',
	'NAME' => 'Tags::Output::LibXML',
	'PREREQ_PM' => {
		'Class::Utils' => 0.01,
		'Error::Pure' => 0.01,
		'File::Object' => 0,
		'Readonly' => 0,
		'Tags' => 0.01,
		'XML::LibXML' => 0,
	},
	'VERSION' => 0.01,
	'test' => {
		'TESTS' => 't/Tags::Output::LibXML/*.t',
	},
);
